DROP TABLE AVALIACAO_COLEGIADO IF EXISTS;
DROP TABLE AVALIACAO_RELATOR IF EXISTS;
DROP TABLE AVALIACAO_SEC_COORD IF EXISTS;
DROP TABLE AVALIACAO_TUTOR IF EXISTS;
DROP TABLE ACG IF EXISTS;
DROP TABLE TIPO_ACG IF EXISTS;
